[package]
name = "eth-runtime"
version = "0.1.0"
authors = ["oasis evm"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
oasis-runtime-sdk = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "b02c8fec4d25508b9e12bb20d334476557b42781" }
oasis-runtime-sdk-evm = { git = "https://github.com/oasisprotocol/oasis-sdk", rev = "b02c8fec4d25508b9e12bb20d334476557b42781" }
cbor = { version = "=0.1.7", package = "oasis-cbor" }

# Third party.
thiserror = "1.0"
